version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r GitHubApi-hw03a/requirements.txt

      - run:
          name: Run GitHub API tests
          command: |
            cd GitHubApi-hw03a
            python -m unittest -v TestGithubApi.py

workflows:
  test-workflow:
    jobs:
      - test